### ISSUE TITLE
Add Save The Children Publishing Agencies To The GB Dashboard

### ISSUE THREAD

**Issue by wendyrogers** [devinit/grand-bargain-monitoring#87]
Save The Children is a new Grand Bargain signatory. As a result the following organisations need to be added to Grand Bargain Transparency Dashboard .

Save The Children International
Save The Children UK
Save The Children Netherlands

**Comment by PetyaKangalova** [comment]
Thanks @wendyrogers  I have now submitted the pull request https://github.com/devinit/grand-bargain-monitoring/pull/88 for Sam to check and merge.

**Comment by samuele-mattiuzzo** [comment]
@Ocre42 can you take a look at this one please? :)
